---
Resources:
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      Policies:
        - PolicyName: update-route53-additional
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action:
              - route53:CreateHostedZone
              - route53:GetHostedZone
              - route53:DeleteHostedZone
              - route53:UpdateHostedZoneComment
              - route53:ListQueryLoggingConfigs
              - iam:CreateServiceLinkedRole 
              Resource: '*'
              Effect: Allow
